# Generated by Django 4.1.3 on 2023-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entry_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccEntry',
            fields=[
                ('pid', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('open_type', models.BooleanField(default=False)),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('open', models.IntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pid'],
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='partial',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='private',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='public',
        ),
        migrations.AddField(
            model_name='entry',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='open',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'None')], default=2),
        ),
        migrations.AddField(
            model_name='entry',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
