# Generated by Django 4.1.3 on 2023-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_accentry_remove_entry_coords_remove_entry_partial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='accentry',
            name='bad_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='busy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='friendly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='friendly_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accentry',
            name='good_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='good_group_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accentry',
            name='hostile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='no_spend_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='quiet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='quiet_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accentry',
            name='spend_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accentry',
            name='spend_pressure_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='friendly',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'None')], default=2),
        ),
        migrations.AddField(
            model_name='entry',
            name='groups',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'None')], default=2),
        ),
        migrations.AddField(
            model_name='entry',
            name='quiet',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'None')], default=2),
        ),
        migrations.AddField(
            model_name='entry',
            name='spend',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'None')], default=2),
        ),
    ]
