# Generated by Django 4.1.3 on 2023-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_contact_accentry_bad_group_accentry_busy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accentry',
            old_name='bad_group',
            new_name='friendly0',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='busy',
            new_name='friendly1',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='closed',
            new_name='groups0',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='friendly',
            new_name='groups1',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='good_group_type',
            new_name='groups_type',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='good_group',
            new_name='open0',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='hostile',
            new_name='open1',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='no_spend_pressure',
            new_name='quiet0',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='open',
            new_name='quiet1',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='quiet',
            new_name='spend0',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='spend_pressure',
            new_name='spend1',
        ),
        migrations.RenameField(
            model_name='accentry',
            old_name='spend_pressure_type',
            new_name='spend_type',
        ),
        migrations.AlterField(
            model_name='entry',
            name='friendly',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False'), (2, 'None')], default=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='groups',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False'), (2, 'None')], default=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='open',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False'), (2, 'None')], default=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quiet',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False'), (2, 'None')], default=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='spend',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False'), (2, 'None')], default=2),
        ),
    ]
