# Generated by Django 4.1.3 on 2023-03-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rename_long_accentry_lng_rename_long_entry_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry", name="comment", field=models.TextField(default=""),
        ),
    ]
