# Generated by Django 4.1.3 on 2023-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_entry_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="accentry", name="address", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="accentry", name="name", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="entry", name="title", field=models.TextField(default=""),
        ),
    ]
