# Generated by Django 4.1.3 on 2023-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_entry_address_entry_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
    ]
