# Generated by Django 4.1.3 on 2023-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_entry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
