# Generated by Django 4.1.3 on 2023-03-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_entry_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accentry",
            name="friendly_type",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accentry",
            name="groups_type",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accentry",
            name="open_type",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accentry",
            name="quiet_type",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="accentry",
            name="spend_type",
            field=models.BooleanField(default=True),
        ),
    ]
