# Generated by Django 4.1.3 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_accentry_friendly_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accentry',
            name='friendly_type',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accentry',
            name='groups_type',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accentry',
            name='open_type',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accentry',
            name='quiet_type',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accentry',
            name='spend_type',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
