# Generated by Django 4.1.3 on 2023-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_accentry_friendly_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("pid", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
