# Generated by Django 4.1.3 on 2023-03-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry", name="reported", field=models.IntegerField(default=0),
        ),
    ]
