# Generated by Django 4.1.3 on 2023-03-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_accentry_friendly_type_and_more"),
        ("api", "0017_alter_entry_reported"),
    ]

    operations = []
