# Generated by Django 4.1.3 on 2023-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_merge_20230307_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="friendly",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="groups",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="open",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="quiet",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="spend",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
