# Generated by Django 4.1.3 on 2023-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_entry_friendly_alter_entry_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address", name="lat", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="address", name="lng", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="address", name="name", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="address",
            name="pid",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
