# Generated by Django 4.1.3 on 2023-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_address_lat_address_lng_address_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
    ]
