version: '3.8'

services:
    frontend:
      image: group-project-frontend
      build: .
      container_name: frontend
      ports:
      - 3000:3000
      volumes: 
      - ./src:/app/src
      - ./public:/app/public