version: '3.8'

services:
    frontend:
      image: group-project-frontend
      build: ./Frontend
      container_name: frontend
      networks:
      - net
      ports:
      - 3000:3000
      volumes: 
      - ./Frontend/src:/app/src
      - ./Frontend/public:/app/public
    backend:
      image: group-project-backend
      build: ./Backend
      container_name: backend
      networks:
      - net
      ports:
      - 8000:8000
      volumes: 
      - ./Backend:/code

networks:
  net: {}